version: '3.5'

services:
  node:
    build: ./.docker/node
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 9229:9229
    #command: nodemon --exec "yarn start"
    command: yarn start
    user: root
